version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: invoice@123
      POSTGRES_DB: invoiceDB
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  db_data:
